file_format: "1"
id: lotus58
name: Lotus58
type: shield
url: https://github.com/ricardo-re-azevedo/zmk-config-lotus58
requires:
  - pro_micro
  - i2c_oled
exposes:
  - nice_view_header
features:
  - keys
  - display
siblings:
  - lotus58_left
  - lotus58_right
